### ISSUE TITLE
issue_commentで、issueの作成者がミュート対象の場合に通知されない？

### ISSUE THREAD

**Issue by book000** [book000/github-webhook-bridge#778]
```text
Request method: POST
Accept: */*
Content-Type: application/json
User-Agent: GitHub-Hookshot/bbf567a
X-GitHub-Delivery: bfacbdc0-45de-11ef-80ff-189038dfc0f0
X-GitHub-Event: issue_comment
X-GitHub-Hook-ID: 442744510
X-GitHub-Hook-Installation-Target-ID: 23239586
X-GitHub-Hook-Installation-Target-Type: organization
X-Hub-Signature: sha1=44f19a457a984ee896645bb8720c224554916ee7
X-Hub-Signature-256: sha256=071067032006ef0085d59604ba7f8fb5aa3485cbc6af7bf88398371b715608f4
```

```json
{
  "action": "created",
  "issue": {
    "url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/issues/191",
    "repository_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt",
    "labels_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/issues/191/labels{/name}",
    "comments_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/issues/191/comments",
    "events_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/issues/191/events",
    "html_url": "https://github.com/jaoafa/VCSpeaker.kt/pull/191",
    "id": 2418797852,
    "node_id": "PR_kwDOJ734E8515LKI",
    "number": 191,
    "title": "chore(deps): update plugin org.jetbrains.kotlin.jvm to v1.9.25",
    "user": {
      "login": "renovate[bot]",
      "id": 29139614,
      "node_id": "MDM6Qm90MjkxMzk2MTQ=",
      "avatar_url": "https://avatars.githubusercontent.com/in/2740?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/renovate%5Bbot%5D",
      "html_url": "https://github.com/apps/renovate",
      "followers_url": "https://api.github.com/users/renovate%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/renovate%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/renovate%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/renovate%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/renovate%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/renovate%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/renovate%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/renovate%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/renovate%5Bbot%5D/received_events",
      "type": "Bot",
      "site_admin": false
    },
    "labels": [

    ],
    "state": "open",
    "locked": false,
    "assignee": null,
    "assignees": [

    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2024-07-19T12:42:57Z",
    "updated_at": "2024-07-19T14:54:07Z",
    "closed_at": null,
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "draft": false,
    "pull_request": {
      "url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/pulls/191",
      "html_url": "https://github.com/jaoafa/VCSpeaker.kt/pull/191",
      "diff_url": "https://github.com/jaoafa/VCSpeaker.kt/pull/191.diff",
      "patch_url": "https://github.com/jaoafa/VCSpeaker.kt/pull/191.patch",
      "merged_at": null
    },
    "body": "[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)\n\nThis PR contains the following updates:\n\n| Package | Change | Age | Adoption | Passing | Confidence |\n|---|---|---|---|---|---|\n| org.jetbrains.kotlin.jvm | `1.9.24` -> `1.9.25` | [![age](https://developer.mend.io/api/mc/badges/age/maven/org.jetbrains.kotlin.jvm/1.9.25?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/org.jetbrains.kotlin.jvm/1.9.25?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/org.jetbrains.kotlin.jvm/1.9.24/1.9.25?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/org.jetbrains.kotlin.jvm/1.9.24/1.9.25?slim=true)](https://docs.renovatebot.com/merge-confidence/) |\n\n---\n\n### Configuration\n\n📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).\n\n🚦 **Automerge**: Enabled.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won't be reminded about this update again.\n\n---\n\n - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box\n\n---\n\nThis PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://developer.mend.io/github/jaoafa/VCSpeaker.kt).\n<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy40MzEuNCIsInVwZGF0ZWRJblZlciI6IjM3LjQzMS40IiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->\n",
    "reactions": {
      "url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/issues/191/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/issues/191/timeline",
    "performed_via_github_app": null,
    "state_reason": null
  },
  "comment": {
    "url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/issues/comments/2239401149",
    "html_url": "https://github.com/jaoafa/VCSpeaker.kt/pull/191#issuecomment-2239401149",
    "issue_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/issues/191",
    "id": 2239401149,
    "node_id": "IC_kwDOJ734E86Feoy9",
    "user": {
      "login": "book000",
      "id": 8929706,
      "node_id": "MDQ6VXNlcjg5Mjk3MDY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8929706?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/book000",
      "html_url": "https://github.com/book000",
      "followers_url": "https://api.github.com/users/book000/followers",
      "following_url": "https://api.github.com/users/book000/following{/other_user}",
      "gists_url": "https://api.github.com/users/book000/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/book000/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/book000/subscriptions",
      "organizations_url": "https://api.github.com/users/book000/orgs",
      "repos_url": "https://api.github.com/users/book000/repos",
      "events_url": "https://api.github.com/users/book000/events{/privacy}",
      "received_events_url": "https://api.github.com/users/book000/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2024-07-19T14:54:06Z",
    "updated_at": "2024-07-19T14:54:06Z",
    "author_association": "MEMBER",
    "body": "@yuuahp jvmの更新、これあげていいですか？ #99 で対応するから上げなくてもいい？",
    "reactions": {
      "url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/issues/comments/2239401149/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  "repository": {
    "id": 666761235,
    "node_id": "R_kgDOJ734Ew",
    "name": "VCSpeaker.kt",
    "full_name": "jaoafa/VCSpeaker.kt",
    "private": false,
    "owner": {
      "login": "jaoafa",
      "id": 23239586,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjIzMjM5NTg2",
      "avatar_url": "https://avatars.githubusercontent.com/u/23239586?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jaoafa",
      "html_url": "https://github.com/jaoafa",
      "followers_url": "https://api.github.com/users/jaoafa/followers",
      "following_url": "https://api.github.com/users/jaoafa/following{/other_user}",
      "gists_url": "https://api.github.com/users/jaoafa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jaoafa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jaoafa/subscriptions",
      "organizations_url": "https://api.github.com/users/jaoafa/orgs",
      "repos_url": "https://api.github.com/users/jaoafa/repos",
      "events_url": "https://api.github.com/users/jaoafa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jaoafa/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/jaoafa/VCSpeaker.kt",
    "description": "🔊 Text channel, now with voice",
    "fork": false,
    "url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt",
    "forks_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/forks",
    "keys_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/teams",
    "hooks_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/hooks",
    "issue_events_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/issues/events{/number}",
    "events_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/events",
    "assignees_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/assignees{/user}",
    "branches_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/branches{/branch}",
    "tags_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/tags",
    "blobs_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/languages",
    "stargazers_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/stargazers",
    "contributors_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/contributors",
    "subscribers_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/subscribers",
    "subscription_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/subscription",
    "commits_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/contents/{+path}",
    "compare_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/merges",
    "archive_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/downloads",
    "issues_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/issues{/number}",
    "pulls_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/labels{/name}",
    "releases_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/releases{/id}",
    "deployments_url": "https://api.github.com/repos/jaoafa/VCSpeaker.kt/deployments",
    "created_at": "2023-07-15T13:43:27Z",
    "updated_at": "2024-07-19T12:42:03Z",
    "pushed_at": "2024-07-19T14:54:06Z",
    "git_url": "git://github.com/jaoafa/VCSpeaker.kt.git",
    "ssh_url": "git@github.com:jaoafa/VCSpeaker.kt.git",
    "clone_url": "https://github.com/jaoafa/VCSpeaker.kt.git",
    "svn_url": "https://github.com/jaoafa/VCSpeaker.kt",
    "homepage": "https://jaoafa.github.io/VCSpeaker.kt/",
    "size": 1698,
    "stargazers_count": 3,
    "watchers_count": 3,
    "language": "Kotlin",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 1,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 29,
    "license": {
      "key": "epl-2.0",
      "name": "Eclipse Public License 2.0",
      "spdx_id": "EPL-2.0",
      "url": "https://api.github.com/licenses/epl-2.0",
      "node_id": "MDc6TGljZW5zZTMy"
    },
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [
      "discord",
      "discord-bot",
      "jaoafa",
      "kordlib",
      "kotlin",
      "read-aloud"
    ],
    "visibility": "public",
    "forks": 1,
    "open_issues": 29,
    "watchers": 3,
    "default_branch": "main",
    "custom_properties": {

    }
  },
  "organization": {
    "login": "jaoafa",
    "id": 23239586,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjIzMjM5NTg2",
    "url": "https://api.github.com/orgs/jaoafa",
    "repos_url": "https://api.github.com/orgs/jaoafa/repos",
    "events_url": "https://api.github.com/orgs/jaoafa/events",
    "hooks_url": "https://api.github.com/orgs/jaoafa/hooks",
    "issues_url": "https://api.github.com/orgs/jaoafa/issues",
    "members_url": "https://api.github.com/orgs/jaoafa/members{/member}",
    "public_members_url": "https://api.github.com/orgs/jaoafa/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/23239586?v=4",
    "description": "jao Community Official Organization. "
  },
  "sender": {
    "login": "book000",
    "id": 8929706,
    "node_id": "MDQ6VXNlcjg5Mjk3MDY=",
    "avatar_url": "https://avatars.githubusercontent.com/u/8929706?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/book000",
    "html_url": "https://github.com/book000",
    "followers_url": "https://api.github.com/users/book000/followers",
    "following_url": "https://api.github.com/users/book000/following{/other_user}",
    "gists_url": "https://api.github.com/users/book000/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/book000/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/book000/subscriptions",
    "organizations_url": "https://api.github.com/users/book000/orgs",
    "repos_url": "https://api.github.com/users/book000/repos",
    "events_url": "https://api.github.com/users/book000/events{/privacy}",
    "received_events_url": "https://api.github.com/users/book000/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

**Comment by book000** [comment]
```
llowed","406":"Not Acceptable","407":"Proxy Authentication Required","408":"Request Timeout","409":"Conflict","410":"Gone","411":"Length Required","412":"Precondition Failed","413":"Payload Too Large","414":"URI Too Long","415":"Unsupported Media Type","416":"Range Not Satisfiable","417":"Expectation Failed","418":"I'm a Teapot","421":"Misdirected Request","422":"Unprocessable Entity","423":"Locked","424":"Failed Dependency","425":"Too Early","426":"Upgrade Required","428":"Precondition Required","429":"Too Many Requests","431":"Request Header Fields Too Large","451":"Unavailable For Legal Reasons","500":"Internal Server Error","501":"Not Implemented","502":"Bad Gateway","503":"Service Unavailable","504":"Gateway Timeout","505":"HTTP Version Not Supported","506":"Variant Also Negotiates","507":"Insufficient Storage","508":"Loop Detected","509":"Bandwidth Limit Exceeded","510":"Not Extended","511":"Network Authentication Required"},"maxHeaderSize":81920,"globalAgent":{"_events":{},"_eventsCount":2,"defaultPort":80,"protocol":"http:","options":{"keepAlive":true,"scheduling":"lifo","timeout":5000,"noDelay":true,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":true,"maxSockets":null,"maxFreeSockets":256,"scheduling":"lifo","maxTotalSockets":null,"totalSocketCount":0}},"https:":{"globalAgent":{"$ref":"$[\"request\"][\"agent\"]"}}},"pathname":"/users/@yuuahp"},"_ended":true,"_ending":true,"_redirectCount":0,"_redirects":{"$ref":"$[\"request\"][\"res\"][\"redirects\"]"},"_requestBodyLength":0,"_requestBodyBuffers":[],"_eventsCount":3,"_currentRequest":{"$ref":"$[\"request\"]"},"_currentUrl":"https://api.github.com/users/@yuuahp"}},"response":{"status":404,"statusText":"Not Found","headers":{"date":"Fri, 19 Jul 2024 14:54:09 GMT","content-type":"application/json; charset=utf-8","x-github-media-type":"github.v3","x-github-api-version-selected":"2022-11-28","access-control-expose-headers":"ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset","access-control-allow-origin":"*","strict-transport-security":"max-age=31536000; includeSubdomains; preload","x-frame-options":"deny","x-content-type-options":"nosniff","x-xss-protection":"0","referrer-policy":"origin-when-cross-origin, strict-origin-when-cross-origin","content-security-policy":"default-src 'none'","vary":"Accept-Encoding, Accept, X-Requested-With","server":"github.com","x-ratelimit-limit":"60","x-ratelimit-remaining":"57","x-ratelimit-reset":"1721403953","x-ratelimit-resource":"core","x-ratelimit-used":"3","content-length":"101","x-github-request-id":"AE80:0A3B:16E1C:18144:669A7E11"},"config":{"$ref":"$[\"config\"]"},"request":{"$ref":"$[\"request\"]"},"data":{"message":"Not Found","documentation_url":"https://docs.github.com/rest","status":"404"}}})
at settle (/var/task/node_modules/axios/dist/node/axios.cjs:1983:12)
at Unzip.handleStreamEnd (/var/task/node_modules/axios/dist/node/axios.cjs:3085:11)
at Unzip.emit (node:events:531:35)
at endReadableNT (node:internal/streams/readable:1696:12)
at processTicksAndRejections (node:internal/process/task_queues:82:21)
at Axios.request (/var/task/node_modules/axios/dist/node/axios.cjs:4224:41)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at GitHubUserMapManager.getFromUsername (/vercel/path0/src/manager/github-user.ts:64:22)
at /vercel/path0/src/actions/issue-comment.ts:153:30
at async Promise.all (index 0)
at IssueCommentAction.getMentions (/vercel/path0/src/actions/issue-comment.ts:151:28)
at IssueCommentAction.onCreated (/vercel/path0/src/actions/issue-comment.ts:38:22)
at Object.hook (/vercel/path0/src/main.ts:78:5)

```
